### ISSUE TITLE
Replace the <fragment> tag with FragmentContainerView.

### ISSUE THREAD

**Issue by mdev88** [murgupluoglu/qrreader-android#1]
Hello, I'm using this library to read QR codes in my app and in the layout xml file I'm seeing this warning:

"Replace the <fragment> tag with FragmentContainerView."

As long as this is a warning I don't mind leaving it that way, but there is a problem when I'm trying to migrate from synthetics to view binding.

Currently I'm accessing the fragment with:

```
val qrCodeReaderView : QRReaderFragment by lazy {
        qrCodeReaderFragment as QRReaderFragment  // qrCodeReaderFragment is the id of the frament in the layout xml
}
```

which requires synthetics. For some reason when I try to access the fragment via the binding instance, I cannot find it, even when the fragment has an ID. 

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityQrBinding.inflate(layoutInflater)
        val view = binding.root
        setContentView(view)

        val qrCodeReaderView : QRReaderFragment by lazy {
            binding.qrCodeReaderFragment as QRReaderFragment  // <-- binding.qrCodeReaderFragment does not exist
        }

        ...
```

I'm new to view binding so I may be doing something wrong, but this is the last piece of code I need to migrate completely to stop using synthetics in my app.

Any help appreciated.

Thanks!

**Comment by murgupluoglu** [comment]
You can access Fragment with

` private lateinit var qrCodeReader: QRReaderFragment`
`qrCodeReader =  supportFragmentManager.findFragmentById(R.id.qrCodeReaderFragment) as QRReaderFragment`

**Comment by mdev88** [comment]
Thanks, that did the trick when still using Fragment in the layout..

![image](https://user-images.githubusercontent.com/7395872/123262008-d1e8a100-d4cd-11eb-84cb-2f00017f661e.png)

If I change it to FragmentContainerView as suggested by the IDE it does't work, but I don't mind that warning. I am now able to complete the migration to View Binding!

Here's the code if it helps anyone else:

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityQrBinding.inflate(layoutInflater)
        val view = binding.root
        setContentView(view)
        
        qrCodeReader = supportFragmentManager.findFragmentById(R.id.qrCodeReaderFragment) as QRReaderFragment

        val qrCodeReaderView : QRReaderFragment by lazy { qrCodeReader }

```
